### ISSUE TITLE
automatic price regulation ?

### ISSUE THREAD

**Issue by Razorxd1993** [Gypopo/EconomyShopGUI-API#1]
Is it possible to insert an automatic price regulation ?
I imagine it like this:

X players sell a certain item 20 times, then the price drops automatically by 10% for example for all players in the store.
Mainly for sale, for purchase it would also be practical.

I hope I am understandable, I use a translator, because I only speak german :)

**Comment by Gypopo** [comment]
This is not the place to ask for feature request on EconomyShopGUI. But a dynamic pricing feature is already requested.
