### ISSUE TITLE
PreTransactionEvent cannot be cancelled

### ISSUE THREAD

**Issue by Aoredon** [Gypopo/EconomyShopGUI-API#2]
Hello, great plugin you have here. Thanks for providing such a great plugin for free.

I'm trying to integrate with the API by hooking the PreTransactionEvent. It seems that this event should be Cancellable, but when setting the event to cancelled it doesn't seem to cancel the event as it still fires like normal. It might also be nice to have a PostTransactionEvent!

**Comment by Gypopo** [comment]
I will have a look into your issue.
And what for exactly do you need the PostTransactionEvent?

**Comment by Aoredon** [comment]
Thanks! And for the PostTransactionEvent it would be useful for integrating with my own plugin to have functionality to be able to know when someone has successfully purchased something from the shop :)

**Comment by Gypopo** [comment]
Latest version of the API and EconomyShopGUI fixes your issue and adds compatibility with a PostTransactionEvent

> Thanks! And for the PostTransactionEvent it would be useful for integrating with my own plugin to have functionality to be able to know when someone has successfully purchased something from the shop :)

**Comment by Aoredon** [comment]
Amazing! Thank you :)
