### ISSUE TITLE
Fake implementation confuses development tools (IntelliJ)

### ISSUE THREAD

**Issue by SpraxDev** [Gypopo/EconomyShopGUI-API#3]
Hi, I'm adding support for your plugin to another one right now and saw that the JetBrains IntelliJ IDE automatically sees that your API method always returns `null`.
![grafik](https://user-images.githubusercontent.com/7331598/199666879-dee9a93b-61d3-47f1-b667-34e072a422d5.png)

It achieves this by automatically generating an `@Contract` annotation for that (`_` stands for any value. so no matter what you put in as first or second argument, it will always return `null`).
![grafik](https://user-images.githubusercontent.com/7331598/199666969-f003f06e-093f-4694-b997-4bfb1162c5c9.png)

Would be nice if this could be improved.

**Comment by Gypopo** [comment]
Just ignore the messages for now, the actual API won't return null.
