### ISSUE TITLE
sellLimitRestockTime is -1 or null

### ISSUE THREAD

**Issue by LucidAPs** [Gypopo/EconomyShopGUI-API#5]
I think that sellLimitRestockTime is not returning the correct values.

[12:33:23 INFO]: DEBUG: Inside the sellLimit <= 0 check
[12:33:23 INFO]: DEBUG: sellLimitRestockTime = -1
[12:33:23 INFO]: DEBUG: sellLimitRestockTime was either null or not greater than 0

config.yml
    material: DIRT
    buy: 100
    sell: 25
    sell-limit-player: 10
    auto-restock-player-sell: 1m

`    
            for (ItemStack itemStack : inventory.getContents()) {
                if (itemStack != null) {
                    ShopItem shopItem = EconomyShopGUIHook.getShopItem(player, itemStack);
                    UUID playerUUID = player.getUniqueId();

                    if (shopItem != null && EconomyShopGUIHook.isSellAble(shopItem)) {
                        int sellLimit = EconomyShopGUIHook.getSellLimit(shopItem, playerUUID);

                        if (sellLimit <= 0) {
                            System.out.println("DEBUG: Inside the sellLimit <= 0 check");
                            Long sellLimitRestockTime = EconomyShopGUIHook.getSellLimitRestockTime(shopItem, playerUUID);
                            System.out.println("DEBUG: sellLimitRestockTime = " + sellLimitRestockTime);

                            if (sellLimitRestockTime != null && sellLimitRestockTime > 0) {
                                System.out.println("DEBUG: Inside the sellLimitRestockTime > 0 check");
                                long seconds = (sellLimitRestockTime / 1000) % 60;
                                long minutes = (sellLimitRestockTime / (1000 * 60)) % 60;
                                long hours = (sellLimitRestockTime / (1000 * 60 * 60)) % 24;

                                String timeString = String.format("%02d:%02d:%02d", hours, minutes, seconds);
                                player.sendMessage(ChatColor.translateAlternateColorCodes('&', "&dShop &8>> &7Sell limit reached for " + itemStack.getType().name() + ". Restocks in: " + timeString));
                            } else {
                                player.sendMessage(ChatColor.translateAlternateColorCodes('&', "&dShop &8>> &7Sell limit reached for " + itemStack.getType().name()));
                                System.out.println("DEBUG: sellLimitRestockTime was either null or not greater than 0");
                            }
                            continue;
                        }

                        Long restockTime = EconomyShopGUIHook.getItemStockRestockTime(shopItem, playerUUID);
                        if (restockTime != null && restockTime > 0) {
                            // Inform player about the restock time
                            long seconds = (restockTime / 1000) % 60;
                            long minutes = (restockTime / (1000 * 60)) % 60;
                            long hours = (restockTime / (1000 * 60 * 60)) % 24;

                            String timeString = String.format("%02d:%02d:%02d", hours, minutes, seconds);
                            player.sendMessage(ChatColor.translateAlternateColorCodes('&', "&dShop &8>> &7Item " + itemStack.getType().name() + " will restock in: " + timeString));
                            continue;
                        }

                        // Adjusting for sell limit
                        int amountToSell = Math.min(itemStack.getAmount(), sellLimit);

                        double price = EconomyShopGUIHook.getItemSellPrice(shopItem, itemStack, player) * amountToSell;
                        if (price > 0) {
                            totalSellPrice += price;
                            int previousCount = itemsSold.getOrDefault(shopItem, 0);
                            itemsSold.put(shopItem, previousCount + amountToSell);

                            EconomyShopGUIHook.sellItemLimit(shopItem, playerUUID, amountToSell);

                            // Remove only the sold items from the inventory
                            itemStack.setAmount(itemStack.getAmount() - amountToSell);
                            if (itemStack.getAmount() <= 0) {
                                inventory.remove(itemStack);
                            }
                        }
                    }
                }
            }

            if (totalSellPrice > 0) {
                EconomyProvider economyProvider = EconomyShopGUIHook.getEcon(null);
                if (economyProvider != null) {
                    economyProvider.depositBalance(player, totalSellPrice);

                    StringBuilder soldItemsMessage = new StringBuilder();
                    for (Map.Entry<ShopItem, Integer> entry : itemsSold.entrySet()) {
                        soldItemsMessage.append(entry.getValue()).append("x ").append(entry.getKey().getItemToGive().getType()).append(", ");
                    }

                    String message = ChatColor.translateAlternateColorCodes('&', "&dShop &8>> &7You sold &d" + soldItemsMessage.toString().trim().replace(" ", ", ") + " &7for &d€" + totalSellPrice);
                    player.sendMessage(message);
                    String consoleMessage = ChatColor.stripColor(message);
                    this.getServer().getConsoleSender().sendMessage(consoleMessage);
                } else {
                    player.sendMessage("Economy provider not found.");
                }
`

**Comment by Gypopo** [comment]
This is only a premium feature, so calls on the API of the free version will always return null.

**Comment by LucidAPs** [comment]
> This is only a premium feature, so calls on the API of the free version will always return null.

I used the premium version for my tests.
