### ISSUE TITLE
getShopItem() not updated to separate files 

### ISSUE THREAD

**Issue by m-surowiec** [Gypopo/EconomyShopGUI-API#8]
https://github.com/Gypopo/EconomyShopGUI-API/blob/79761ec2dd4cf55bc1822f1bc42e44fd28db5c28/src/main/java/me/gypopo/economyshopgui/api/EconomyShopGUIHook.java#L626

This method wasn't updated since the sections files got separeted and there now is no way to use it.
All sections are now in individual files, not shops.yml and I can't input the section file to the method

**Comment by m-surowiec** [comment]
@Gypopo

**Comment by Gypopo** [comment]
All methods are tested and working on the new config layout we inplemented over a year ago, please debug your own code.

**Comment by m-surowiec** [comment]
https://github.com/Gypopo/EconomyShopGUI-API/blob/79761ec2dd4cf55bc1822f1bc42e44fd28db5c28/src/main/java/me/gypopo/economyshopgui/api/EconomyShopGUIHook.java#L622C6-L622C57

There is no shops.yml file. How should the itemPath look? `file/s1.s2`?

**Comment by Gypopo** [comment]
The itempath is formatted as <section>.<itemIndex>, see here on how to check the item path/index of items: https://wiki.gpplugins.com/economyshopgui/basics/how-to#obtaining-item-indexes-of-shop-items
